USE AdventureWorks2014;

SELECT * FROM HumanResources.Department;

SELECT Name FROM HumanResources.Department;

SELECT GroupName FROM HumanResources.Department;

SELECT DISTINCT GroupName FROM HumanResources.Department;

SELECT Name,GroupName FROM HumanResources.Department WHERE GroupName like 'Manufacturing';

SELECT * FROM HumanResources.Employee;

SELECT * FROM HumanResources.Employee WHERE OrganizationLevel IN (2,4);

SELECT JobTitle,COUNT(JobTitle) AS Totalcount FROM HumanResources.Employee GROUP BY JobTitle ;

SELECT * FROM HumanResources.Employee WHERE JobTitle LIKE 'FACILITIES MANAGER';

SELECT * FROM HumanResources.Employee WHERE JobTitle LIKE '%MANAGER%';

SELECT * FROM HumanResources.Employee WHERE BirthDate > '1980-01-01';

SELECT * FROM HumanResources.Employee WHERE BirthDate > '1980-01-01' ORDER BY BirthDate;

SELECT * FROM HumanResources.Employee WHERE BirthDate > '1970-01-01' AND BirthDate < '1980-01-01' ORDER BY BirthDate;

SELECT * FROM HumanResources.Employee WHERE BirthDate BETWEEN '1970-01-01'AND '1980-01-01';

SELECT * FROM Production.Product;

SELECT ProductID,Name,SafetyStockLevel INTO PERMTable FROM Production.Product WHERE DaysToManufacture = 0 AND Color LIKE 'BLACK' AND FinishedGoodsFlag = 0;

SELECT * FROM PERMTable;

DELETE FROM PERMTable WHERE Name LIKE 'Chainring';

SELECT * FROM PERMTable;

UPDATE PERMTable SET Name = 'KILLER MILLER'  WHERE Name like 'ML%' ;

SELECT * FROM Production.Product;

SELECT TOP(12) * FROM Production.Product;

SELECT NAME, LISTPRICE, LISTPRICE + 10 AS ADJUSTED_LIST_PRICE  INTO #TempTable FROM Production.Product;

SELECT * FROM #TempTable;

CREATE TABLE MYEMPLOYEE (EMPLOYEEID INT, FIRSTNAME VARCHAR(20), LASTNAME VARCHAR(20));

CREATE TABLE MYSALARY (EMPLOYEEID INT, SALARY FLOAT);

INSERT INTO MYEMPLOYEE VALUES (1, 'Michael', 'Scott');

INSERT INTO MYEMPLOYEE VALUES (2, 'Pam', 'Beesly');

INSERT INTO MYEMPLOYEE VALUES (3, 'Dwight', 'Schutte');

INSERT INTO MYEMPLOYEE VALUES (4, 'RAKESH', 'ROSHAN');

INSERT INTO MYEMPLOYEE VALUES (4, 'SAM', 'CURRAN');

INSERT INTO MYSALARY VALUES (1, 10000);

INSERT INTO MYSALARY VALUES (2, 8000);

INSERT INTO MYSALARY VALUES (3, 6000);

INSERT INTO MYSALARY VALUES (4, 6000);

INSERT INTO MYSALARY VALUES (5, 6000);


SELECT * FROM MYSALARY;

SELECT * FROM MYEMPLOYEE;

CREATE TABLE STUDENTDETAILS (ROLLNUM INT,NAME VARCHAR(50),SUBJECT VARCHAR(20));

INSERT INTO STUDENTDETAILS VALUES ( 1,'DHIRAJ','MATH');

INSERT INTO STUDENTDETAILS VALUES ( 1,'KUMAR','SCIENCE');

INSERT INTO STUDENTDETAILS VALUES ( 1,'SHARMA','ENGLISH');

SELECT * FROM STUDENTDETAILS;

TRUNCATE TABLE STUDENTDETAILS;

SELECT * FROM STUDENTDETAILS;

DROP TABLE  STUDENTDETAILS;

SELECT GETDATE();

SELECT GETDATE()-4;

SELECT DATEPART(DD,GETDATE());

SELECT DATEPART(MM,GETDATE());

SELECT DATEPART(YYYY,GETDATE());

SELECT DATEADD(DD,7,GETDATE());

SELECT DATEADD(DD,3,'2005-01-02');

SELECT DATEADD(MM,7,'2005-01-02');

SELECT DATEADD(YYYY,15,'2005-01-02');

SELECT DATEDIFF(DD,'2020-06-01',GETDATE());

SELECT DATEDIFF(MM,'2020-01-01',GETDATE());

SELECT DATEDIFF(YYYY,'1994-01-01',GETDATE());

SELECT (DATEADD(dd, -(DATEPART(day, GETDATE()) - 1), GETDATE()))

SELECT (DATEADD(DD,-(DATEPART(DD,GETDATE() - 1)),GETDATE()));

SELECT * FROM MYSALARY;

SELECT AVG(SALARY) FROM MYSALARY;

SELECT COUNT(*) FROM MYSALARY;

SELECT SUM(SALARY) FROM MYSALARY;

SELECT MAX(SALARY) FROM MYSALARY;

SELECT MIN(SALARY) FROM MYSALARY;

CREATE TABLE MYORDER (ORDERNUMBER INT, ORDERNAME VARCHAR(20), CUSTOMERID INT);

INSERT INTO MYORDER VALUES (1, 'SOMEORDER1', 1);

INSERT INTO MYORDER VALUES (2, 'SOMEORDER2', 2);

INSERT INTO MYORDER VALUES (3, 'SOMEORDER3', 7);

INSERT INTO MYORDER VALUES (4, 'SOMEORDER4', 8);

SELECT * FROM MYORDER;


CREATE TABLE MYCUSTOMER(CUSTOMERID INT, CUSTOMERNAME VARCHAR(20));

TRUNCATE TABLE MYCUSTOMER;

INSERT INTO MYCUSTOMER VALUES (1, 'RAKESH');

INSERT INTO MYCUSTOMER VALUES (3, 'JOHN');


SELECT * FROM MYCUSTOMER;
SELECT * FROM MYORDER;

SELECT CUSTOMERID,ORDERNAME,CONCAT(CUSTOMERID,'=',ORDERNAME) AS ConcatinatedText FROM MYORDER;

SELECT CUSTOMERID,ORDERNAME,CONCAT(CUSTOMERID,'=',RAND()) AS ConcatinatedText FROM MYORDER;

SELECT ORDERNAME,LEFT(ORDERNAME,5)AS SplittedString FROM MYORDER;

SELECT ORDERNAME,RIGHT(ORDERNAME,3)AS SplittedString FROM MYORDER;

SELECT ORDERNAME,LOWER(ORDERNAME)AS ConvertedString FROM MYORDER;

SELECT ORDERNAME,LOWER(ORDERNAME)AS ConLOWERString,UPPER(ORDERNAME)AS ConUPPERString  FROM MYORDER;

SELECT ORDERNAME,LEN(ORDERNAME)AS LenghtofString  FROM MYORDER;

SELECT '        DHIRAJ          ';

SELECT LEN('        DHIRAJ          ');

SELECT LTRIM('        DHIRAJ          ');

SELECT RTRIM('        DHIRAJ          ');


SELECT RTRIM(LTRIM('        DHIRAJ          '));


SELECT * FROM MYSALARY;

SELECT * FROM MYEMPLOYEE;

SELECT A.EMPLOYEEID,A.FIRSTNAME,A.LASTNAME,B.SALARY FROM MYEMPLOYEE A INNER JOIN MYSALARY B ON A.EMPLOYEEID = B.EMPLOYEEID;

CREATE TABLE MYPHONE (EMPLOYEEID INT, PHONNENUMBER INT);

INSERT INTO MYPHONE VALUES (1, 1211123342);

INSERT INTO MYPHONE VALUES (2, 1111111111);

SELECT * FROM MYPHONE;

SELECT * FROM MYEMPLOYEE;

SELECT B.EMPLOYEEID,B.PHONNENUMBER,A.FIRSTNAME,A.LASTNAME FROM MYEMPLOYEE A LEFT JOIN MYPHONE B ON A.EMPLOYEEID = B.EMPLOYEEID;

SELECT B.EMPLOYEEID,B.PHONNENUMBER,A.FIRSTNAME,A.LASTNAME FROM MYEMPLOYEE A RIGHT JOIN MYPHONE B ON A.EMPLOYEEID = B.EMPLOYEEID;


SELECT B.PHONNENUMBER,A.FIRSTNAME, A.LASTNAME FROM MYEMPLOYEE A LEFT JOIN MYPHONE B ON A.EMPLOYEEID = B.EMPLOYEEID;

CREATE TABLE MYPARKING (EMPLOYEEID INT, PARKINGSPOT VARCHAR(20));

INSERT INTO MYPARKING VALUES (1, 'A1');

INSERT INTO MYPARKING VALUES (2, 'A2');

SELECT * FROM MYPARKING;

SELECT * FROM MYEMPLOYEE;

SELECT  B.FIRSTNAME, B.LASTNAME,A.PARKINGSPOT FROM MYPARKING A RIGHT JOIN MYEMPLOYEE B ON A.EMPLOYEEID = B.EMPLOYEEID

DROP TABLE MYCUSTOMER;

DROP TABLE MYORDER;

CREATE TABLE MYCUSTOMER(CUSTOMERID INT, CUSTOMERNAME VARCHAR(20));

INSERT INTO MYCUSTOMER VALUES (1, 'RAKESH');

INSERT INTO MYCUSTOMER VALUES (3, 'JOHN');

CREATE TABLE MYORDER (ORDERNUMBER INT, ORDERNAME VARCHAR(20), CUSTOMERID INT);

INSERT INTO MYORDER VALUES (1, 'SOMEORDER1', 1);

INSERT INTO MYORDER VALUES (2, 'SOMEORDER2', 2);

INSERT INTO MYORDER VALUES (3, 'SOMEORDER3', 7);

INSERT INTO MYORDER VALUES (4, 'SOMEORDER4', 8);

SELECT * FROM MYCUSTOMER;

SELECT CUSTOMERID,ORDERNAME,ORDERNUMBER FROM MYORDER;

SELECT A.CUSTOMERID,  A.CUSTOMERNAME, B.ORDERNUMBER, B.ORDERNAME, B.ORDERNAME  FROM MYCUSTOMER A FULL OUTER JOIN MYORDER B ON A.CUSTOMERID = B.CUSTOMERID

SELECT * FROM MYEMPLOYEE;

SELECT * FROM MYSALARY;

SELECT * FROM MYEMPLOYEE CROSS JOIN MYSALARY;

DELETE FROM MYEMPLOYEE WHERE EMPLOYEEID =4;

DELETE FROM MYSALARY WHERE EMPLOYEEID IN(4,5);